### ISSUE TITLE
Save/Update are not working not working in 5.5

### ISSUE THREAD

**Issue by maxvaser** [jarektkaczyk/eloquence#205] opened 2017-10-23 15:42 UTC
Hi, 

Save/Update are not working for models using eloquence 5.5. It returns as though it saved, but the database record doesn't actually update. Create works fine, just not save & update. I removed the use Eloquence; off the model and the records save/update in the database as expected. 

Are there any additional requirements in 5.5 for that normal functionality to still work? I couldn't see anything in the documentation. 

Thank you!!

**Comment by mmaedler** [comment] 2017-10-24 10:28
I'm facing the same issue and traced it down to `lluminate\Database\Eloquent\Concerns\HasAttributes::hasChanges`. In this method the `$attributes` parameter looks as follows: 
`
array(1) {
  [0]=>
  NULL
}
`
which leads the check in line 997 to fail. This then results in a falsy returned "false" since no change of the attributes is detected.
I have replaced the line 997 from like follows:
```
< if (empty($attributes)) {
> if (empty($attributes) || (count($attributes) == 1 && $attributes[0] === null) ) {
```
That is for sure not the root cause, but fixes the problem for now.

**Comment by HPRyan** [comment] 2017-10-27 10:44
I have also experienced this.

Seems to be `\Sofa\Hookable\Hookable::isDirty`.

Because the default is `null` then this is being passed through to `\Illuminate\Database\Eloquent\Concerns\HasAttributes::isDirty` as `null` rather than empty so `func_get_args()` is picking this up.

Until there is an official fix I have patched this by adding an additional check to `\Sofa\Hookable\Hookable::isDirty`.

```
if ($attributes === null) {
    $attributes = [];
}
```

**Comment by mmaedler** [comment] 2017-10-27 11:07
There's also a pending PR in sofa/hookable: https://github.com/jarektkaczyk/hookable/issues/15

**Comment by HPRyan** [comment] 2017-10-27 11:33
Cheers for linking the PR, checked this out in composer for now.

**Comment by mmaedler** [comment] 2017-10-30 09:09
You're welcome. Can you share how you had checked it out via composer? For me its failing... Thanks!

**Comment by trahma** [comment] 2017-11-07 00:09
Experiencing this issue as well.  Would love to have it merged with the master branch.

**Comment by trahma** [comment] 2017-11-07 00:29
@mmaedler you can do so by adding the following to your composer.json..
```    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/EricTendian/hookable"
        }
    ]```

**Comment by dstollie** [comment] 2017-11-10 10:38
Thanks @trahma but this should really be added to the main repo

**Comment by agonzalezml** [comment] 2017-11-16 12:42
I'm having this problem too...

**Comment by kevdotbadger** [comment] 2017-11-17 13:37
@jarektkaczyk Any chance of adding this to the main branch? Solution works for me.

**Comment by jarektkaczyk** [comment] 2017-11-17 14:13
merged folks, should run smoothly now.
cheers!

**Closed by jarektkaczyk** 2017-11-17 14:13 UTC
